Run XManager Vizier hyperparameter sweep on GPU
instadeepai/skai pull request #4
Opened 2023-08-23 06:25 UTC by panford

## Description
This feature enables XManager vizier hyperparameter sweep done faster on GPUs.

Jobs sent to Google Cloud Dataflow requires that the local environment version of python and apache-beam versions are the same in container image. Currently, we have support for python versions 3.8-3.11 and soon to extend to python 3.7 and apache-beam version 2.49.0.

## Types of changes
New docker images created from tensorflow-gpu base image. 
GPU machine and worker type default configurations added

## What changes does to code
Adds new feature:- XManager + Vertex AI + Vizier on GPUs

2023-08-23 06:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/instadeepai/skai?pullRequest=4) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/instadeepai/skai?pullRequest=4) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/instadeepai/skai?pullRequest=4) it.</sub>

2023-08-24 08:56 UTC, Alikerin requested changes
I left a few suggestions.
Please take a look.
Thank you.

2023-08-24 08:56 UTC, Alikerin commented on src/skai/model/xmanager_external_metric_logger.py
> +#     VizierWorker  # Open-source manager-Deepmind
can we remove these commented lines?

2023-08-24 08:56 UTC, Alikerin commented on src/skai/model/xm_launch_single_model_vertex.py
> +    return base_image, docker_instructions
Can we move these docker stuff to a different file?

2023-08-24 08:56 UTC, Alikerin commented on src/skai/model/xm_launch_single_model_vertex.py
> +def construct_docker_instructions(accelerator: str) -> Tuple[str, List[str]]:
Would it be better if we name this function as `get_docker_instructions`?

2023-08-24 08:56 UTC, Alikerin commented on src/skai/model/xm_launch_single_model_vertex.py
> +        base_image=base_image, #'gcr.io/deeplearning-platform-release/base-gpu',
can you remove the commented image here?

2023-08-24 08:58 UTC, Alikerin commented
In the description you mention Vizier and DataFlow, is this PR related to both?

2023-08-24 08:59 UTC, Alikerin commented
Also try fix the conflicts with instadeep branch

2023-08-24 09:58 UTC, panford commented on src/skai/model/xm_launch_single_model_vertex.py
> +def construct_docker_instructions(accelerator: str) -> Tuple[str, List[str]]:
yes, that makes more sense

2023-08-24 15:47 UTC, Alikerin approved these changes

2023-08-24 15:47 UTC, Alikerin approved these changes

2023-08-24 15:48 UTC, merged